Cpu efficiency
MonALISA-CIT/apmon_java pull request #5
Opened 2022-03-28 14:37 UTC by bertranf

2022-04-01 07:58 UTC, costing requested changes

2022-04-01 07:58 UTC, costing commented on src/apmon/MonitoredJob.java
> +		ret.put(ApMonMonitoringConstants.LJOB_CPU_TIME, Double.valueOf(totalCPUTime/hertz));
Shouldn't `hertz` be set to 1 if (!isLinux)? Otherwise this will cause a division by zero

2022-04-01 07:58 UTC, costing commented on src/apmon/MonitoredJob.java
> +						String[] splitted = s.split(" ");
Check that the `split()` result has at least 15 elements

2022-04-01 07:58 UTC, costing commented on src/apmon/MonitoredJob.java
> +					instantCpuEfficiency = cpuEfficiency;
Is `instantCpuEfficiency` correct? Shouldn't it be the delta(cpu time of the child processes) / delta(wall time)?

2022-04-04 09:14 UTC, bertranf commented on src/apmon/MonitoredJob.java
> +					instantCpuEfficiency = cpuEfficiency;
In this case, it is just sampling so we do not have any record of the previous values. That's why CPU efficiency and CPU instant efficiency are set to the same value...

2022-04-13 07:45 UTC, costing commented on src/apmon/MonitoredJob.java
> +				instantCpuEfficiency =  100000 * (totalCPUTime - previousTotalCPUTime) / (currentMeasureTime - previousMeasureTime);
I think you should use `hertz * 1000` instead of `100000`

2022-04-13 07:45 UTC, costing commented on src/apmon/MonitoredJob.java
> +	public Vector<Integer> getChildren(int targetPid) {
Public methods should not change signature

2022-04-13 07:51 UTC, bertranf commented on src/apmon/MonitoredJob.java
> +				instantCpuEfficiency =  100000 * (totalCPUTime - previousTotalCPUTime) / (currentMeasureTime - previousMeasureTime);
No, because here we are getting the time from the output of ps, and it is already in seconds, not in cycles. The 100000 comes from putting together the conversion of the time difference and the 100 to get the percentage

2022-06-02 13:11 UTC, merged